//I have put the char infront to Differ between Shift and normal key but also to get this in the order I added because if I don't do this forEach will order this in the numeric way
var settings = 
{ 
    layout:
    {
        "german":
        {
            
             "S0":"...None..."
            ,"S49":"1"
            ,"S50":"2"
            ,"S51":"3"
            ,"S52":"4"
            ,"S53":"5"
            ,"S54":"6"
            ,"S55":"7"
            ,"S56":"8"
            ,"S57":"9"
            ,"S48":"0"
            ,"S97":"a"
            ,"S39":"&auml;"
            ,"S98":"b"
            ,"S99":"c"
            ,"S100":"d"
            ,"S101":"e"
            ,"S102":"f"
            ,"S103":"g"
            ,"S104":"h"
            ,"S105":"i"
            ,"S106":"j"
            ,"S107":"k"
            ,"S108":"l"
            ,"S109":"m"
            ,"S110":"n"
            ,"S111":"o"
            ,"S59":"&ouml;"
            ,"S112":"p"
            ,"S113":"q"
            ,"S114":"r"
            ,"S115":"s"
            ,"S116":"t"
            ,"S117":"u"
            ,"S91":"&uuml;" //ü
            ,"S118":"v"
            ,"S119":"w"
            ,"S120":"x"
            ,"S121":"z"
            ,"S122":"y"
            ,"S176":"RETURN"
            ,"S177":"ESC"
            ,"S178":"BCKSPC"
            ,"S179":"TAB"
            ,"S32":"SPC"

            ,"S96":"^"
            ,"S126":"&deg;" //°
            ,"S33":"!"
            ,"S64":"&quot;" //"
            ,"S35":"&sect;" //§
            ,"S36":"$"
            ,"S37":"%"
            ,"S94":"&amp;" //&
            ,"S38":"/"
            ,"S42":"("
            ,"S40":")"
            ,"S41":"="
            ,"S45":"&szlig" //ß
            ,"S95":"?"
            ,"S61":"&lsquo;"
            ,"S43":"&rsquo;"
            
            ,"S93":"+"
            ,"S125":"*"
            ,"S92":"<"
            ,"S124":">"
            ,"S44":","
            ,"S60":";"
            ,"S46":"."
            ,"S62":":"
            ,"S47":"-"
            ,"S63":"_"


            ,"S194":"F1"
            ,"S195":"F2"
            ,"S196":"F3"
            ,"S197":"F4"
            ,"S198":"F5"
            ,"S199":"F6"
            ,"S200":"F7"
            ,"S201":"F8"
            ,"S202":"F9"
            ,"S203":"F10"
            ,"S204":"F11"
            ,"S205":"F12"
            ,"S19":"Pause"
            ,"S211":"Pg up"
            ,"S214":"Pg down"
            ,"S213":"end"
            ,"S210":"home"
            ,"S216":"left arrow"
            ,"S218":"up arrow"
            ,"S215":"right arrow"
            ,"S217":"down arrow"
            ,"S209":"insert"
            ,"S212":"delete"
            ,"F0":"None..."
            ,"F1":"Left SHIFT"
            ,"F2":"Left ALT"
            ,"F3":"Left CTRL"
            ,"F4":"L Shift + L ALT"
            ,"F5":"L Shift +  CTRL"
            ,"F6":"Alt + CTRL"
            ,"F7":"L Shift + Alt + CTRL"
            ,"F20":"Mouse Button Left"
            ,"F21":"Mouse Button Right"
            ,"F22":"Mouse Button Middle"
            ,"F23":"Mouse Button Left + SHIFT"
            ,"F24":"Mouse Button Right + SHIFT"
            ,"F25":"Mouse Button Middle + SHIFT"
            ,"A26":"Mouse Button Left DBLClick"
            ,"A30":"Mouse Move"
            ,"A50":"Vol MUTE"
            ,"A51":"Vol -"
            ,"A52":"Vol +"
        }
        ,"english":{"S0":"None","F2":"None"}
    }
};